version: '3'
services:
  mariadb:
    networks:
      - backend
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DB_PASSWORD
      MYSQL_DATABASE: sorafuru
      MYSQL_USER: DB_USERNAME
      MYSQL_PASSWORD: DB_PASSWORD
    ports:
      - "3306:3306"
    # volumes:
    #   - ./data:/var/lib/mysql
networks:
  backend:
    driver: bridge
